version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: gateway/target/gateway-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - worker-service-1
      - worker-service-2
      - worker-service-3
    environment:
      - JAVA_OPTS=-Dserver.tomcat.threads.max=10 -Dserver.tomcat.threads.min-spare=10 
    networks:
      - my-network

  worker-service-1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: worker-service/target/worker-service-0.0.1-SNAPSHOT.jar
    environment:
      - WAIT_TIME_SECONDS=30
    networks:
      - my-network

  worker-service-2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: worker-service/target/worker-service-0.0.1-SNAPSHOT.jar
    environment:
      - WAIT_TIME_SECONDS=10
    networks:
      - my-network
    
  worker-service-3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: worker-service/target/worker-service-0.0.1-SNAPSHOT.jar
    environment:
      - WAIT_TIME_SECONDS=2
    networks:
      - my-network

  request-data:
    image: alpine
    volumes:
      - ./data-fetcher.sh:/data-fetcher.sh
    command: sh -c "apk add --no-cache curl && sh /data-fetcher.sh"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
